apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: wilsonlau/mlops-training-docker:latest
        ports: 
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  ports:
  - name: http
    protocol: TCP
    port: 5001
    targetPort: 5001
  type: LoadBalancer